<?xml version ="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name ="car">
  <xacro:property name="PI" value="3.1415926535897931"/>
  
  <xacro:property name="half_front_track_width" value="0.819" />
  <xacro:property name="half_rear_track_width" value="0.8" />
  <xacro:property name="half_wheelbase" value="1.326" />
  
  <xacro:property name="wheel_radius" value="0.36" />
  <xacro:property name="wheel_thickness" value="0.25" />
  <xacro:property name="wheel_mass" value="40.0" />
  <xacro:property name="body_mass" value="1620.0" />

  <xacro:property name="body_width" value="${2*half_rear_track_width}" />
  <xacro:property name="body_depth" value="${2*half_wheelbase + 0.8}" />
  <xacro:property name="body_length" value="0.6" />
    <!-- <link name="base_footprint"/> -->
  <xacro:include filename="$(find car_description)/urdf/car_gazebo.urdf.xacro"/>
    
    <link name ="base_link">
        <visual>
            <origin rpy="0 0 0" xyz="0.035 0 0.025"/>
            <geometry>
                <mesh filename="package://car_description/meshes/orange_body.dae"/>
            </geometry>
        </visual>    
    
        <collision>
      <origin xyz="0.035 0 0.025" rpy="0 0 0" />
      <geometry>
                <mesh filename="package://car_description/meshes/body_collision.stl"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${body_mass}"/>
      <inertia ixx="${body_mass/12 * (body_width*body_width + body_length*body_length)}" ixy="0" ixz="0" iyy="${body_mass/12 * (body_length*body_length + body_depth*body_depth)}" iyz="0" izz="${body_mass/12 * (body_width*body_width + body_depth*body_depth)}"/>
    </inertial>



    </link>

    <!-- <joint name ="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link ="base_link"/>
        <origin rpy="0 0 0 " xyz ="1.326 0 0.36"/>
    </joint> -->
<!-- back right -->
    
    
    
    
    
    
    
    <link name ="wheel_right_link">
        <visual>
            <origin rpy="1.57079632679 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://car_description/meshes/wheel.dae"/>
            </geometry>
        </visual>    
    
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0" ixz="0" iyy="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0" izz="${wheel_mass/2 * wheel_radius*wheel_radius}"/>
        </inertial>
    
    </link>


    <joint name ="wheel_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link ="wheel_right_link"/>
        <axis xyz ="0 0 1 "/>
        <origin rpy="-1.57079632679 0 0 " xyz ="-1.326 -0.8 0"/>
    </joint>
<!-- back left -->
    
    
    
    <link name ="wheel_left_link">
        <visual>
            <origin rpy="1.57079632679 3.1415926535 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://car_description/meshes/wheel.dae"/>
            </geometry>
        </visual>    
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0" ixz="0" iyy="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0" izz="${wheel_mass/2 * wheel_radius*wheel_radius}"/>
        </inertial>
    </link>


    <joint name ="wheel_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link ="wheel_left_link"/>
        <axis xyz ="0 0 1 "/>
        <origin rpy="-1.57079632679 0 0 " xyz ="-1.326 0.8 0"/>
    </joint>
<!-- front left -->
    
    
   
   
   
   
   
   
    <link name ="wheel_front_left_link">
        <visual>
            <origin rpy="1.57079632679 3.1415926535 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://car_description/meshes/wheel.dae"/>
            </geometry>
        </visual>   

      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0" ixz="0" iyy="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0" izz="${wheel_mass/2 * wheel_radius*wheel_radius}"/>
      </inertial>


    </link>

    <link name="steer_front_left_link" >
      <inertial>
        <origin xyz="-0.013054 -0.0295 0" rpy="0 0 0"/>
        <mass value="20.0"/>
        <inertia ixx="2" ixy="0" ixz="0" iyy="2" iyz="0" izz="2"/>
      </inertial>
    </link>

   
    <joint name="steer_front_left_joint" type="revolute" >
      <parent link="base_link" />
      <child link="steer_front_left_link" />
      <origin xyz="1.326 0.8 0" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <limit upper="0.6" lower="-0.6" effort="-1.0" velocity="-1.0" />
    </joint>

    <joint name ="wheel_front_left_joint" type="continuous">
        <parent link="steer_front_left_link"/>
        <child link ="wheel_front_left_link"/>
        <axis xyz ="0 0 1 "/>
        <origin rpy="-1.57079632679 0 0 " xyz ="0 0 0"/>
    </joint>

<!-- front right -->
    
    
    
    
    
    
    <link name ="wheel_front_right_link">
        <visual>
            <origin rpy="1.57079632679 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://car_description/meshes/wheel.dae"/>
            </geometry>
        </visual>    

      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0" ixz="0" iyy="${wheel_mass/12*(3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0" izz="${wheel_mass/2 * wheel_radius*wheel_radius}"/>
      </inertial>

    </link>

    <link name="steer_front_right_link" >
      <inertial>
        <origin xyz="-0.013054 -0.0295 0" rpy="0 0 0"/>
        <mass value="20.0"/>
        <inertia ixx="2" ixy="0" ixz="0" iyy="2" iyz="0" izz="2"/>
      </inertial>
    </link>

   <joint name ="wheel_front_right_joint" type="continuous">
        <parent link="steer_front_right_link"/>
        <child link ="wheel_front_right_link"/>
        <axis xyz ="0 0 1 "/>
        <origin rpy="-1.57079632679 0 0 " xyz ="0 0 0"/>
    </joint>

    <joint name="steer_front_right_joint" type="revolute" >
      <parent link="base_link" />
      <child link="steer_front_right_link" />
      <origin xyz="1.326 -0.8 0" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <limit upper="0.7" lower="-0.7" effort="0.0" velocity="0.0" />
    </joint>    


</robot>